@startuml
'https://plantuml.com/sequence-diagram

!theme plain
autonumber

boundary Main
database Input
participant InputDataProvider
participant OsmoGridGuardian
participant LvCoordinator
collections LvRegionCoordinator
collections MunicipalityCoordinator
collections DistrictCoordinator
collections SubDistrictCoordinator
collections LvGridGenerator
participant ResultListener

== Init ==
Main -> OsmoGridGuardian: Run(cfg)
OsmoGridGuardian --> InputDataProvider: //Spawn//

OsmoGridGuardian --> ResultListener: //Spawn//
note right: Death watch of\n""ResultListener""

== LV generation ==
OsmoGridGuardian --> LvCoordinator: //Spawn//
OsmoGridGuardian -> LvCoordinator: <font color="red">!</font>ReqLvGrids(...)
LvCoordinator -> InputDataProvider: <font color="red">!</font>ReqOsm(...)
InputDataProvider <--> Input: //Read//
LvCoordinator -> InputDataProvider: <font color="red">!</font>ReqAssetTypes(...)
InputDataProvider <--> Input: //Read//
InputDataProvider -> LvCoordinator: <font color="red">!</font>RepOsm(...)
InputDataProvider -> LvCoordinator: <font color="red">!</font>RepAssetTypes(...)
note right: Determine the highest\nadministrative boundary //n//
LvCoordinator --> LvGridGenerator: //Spawn worker pool//
LvCoordinator --> SubDistrictCoordinator: //Spawn worker pool//
LvCoordinator --> DistrictCoordinator: //Spawn worker pool//
LvCoordinator --> MunicipalityCoordinator: //Spawn worker pool//
LvCoordinator --> LvRegionCoordinator: //Spawn worker pool//
note right: Within a worker pool the\n""LvRegionCoordinator"" has\nto maintain a list of regions,\nit awaits completion\nmessages for

LvCoordinator -> LvRegionCoordinator: <font color="red">!</font>Partition(Region, n)
note right: //n// is the highest apparent\nadministrative boundary\nwithin OSM data
LvRegionCoordinator -> LvRegionCoordinator: <font color="red">!</font>Partition(Region, n')
... **Recursively divide regions until administrative boundary of a municipality is reached** ...

LvRegionCoordinator -> MunicipalityCoordinator: <font color="red">!</font>HandleMunicipality(Region)

MunicipalityCoordinator -> DistrictCoordinator: <font color="red">!</font>HandleDistrict(Region)

DistrictCoordinator -> SubDistrictCoordinator: <font color="red">!</font>HandleSubDistrict(Region)

SubDistrictCoordinator -> LvGridGenerator: <font color="red">!</font>BuildGridModel(Region)

activate LvGridGenerator
SubDistrictCoordinator -> DistrictCoordinator: <font color="red">!</font>Done(amountOfGrids)
DistrictCoordinator -> MunicipalityCoordinator: <font color="red">!</font>Done(amountOfGrids)
MunicipalityCoordinator -> LvRegionCoordinator: <font color="red">!</font>Done(amountOfGrids)
LvRegionCoordinator -> LvRegionCoordinator: <font color="red">!</font>Done(amountOfGrids)
... **Report recursively until all intermediate levels are passed** ...
LvRegionCoordinator -> LvCoordinator: <font color="red">!</font>Done(amountOfGrids)
... ...
LvGridGenerator -> LvCoordinator: <font color="red">!</font>PepLvGrid(...)
deactivate LvGridGenerator

LvCoordinator -> OsmoGridGuardian: <font color="red">!</font>RepLvGrids(...)
note right: TODO: Tear down worker pools

== MV generation ==
... **To be defined in a later stage** ...

== Result handling ==
OsmoGridGuardian -> ResultListener: <font color="red">!</font>GridResult(...)
activate ResultListener
... ...
ResultListener -> OsmoGridGuardian: <font color="red">!</font>ResultListenerDied
deactivate ResultListener
OsmoGridGuardian -> InputDataProvider: <font color="red">!</font>Terminate(...)
InputDataProvider <--> Input: //Close//
InputDataProvider -> OsmoGridGuardian: <font color="red">!</font>InputDataProviderDied

OsmoGridGuardian -> Main: <font color="red">!</font>Done

'TODO: Don't forget to spawn and initialize the ResultListener

@enduml
