@startuml
'https://plantuml.com/sequence-diagram

!theme plain
autonumber

boundary Main
database Input
participant InputDataProvider
participant OsmoGridGuardian
participant LvCoordinator
participant LvRegionCoordinator
participant MunicipalityCoordinator
participant DistrictCoordinator
participant SubDistrictCoordinator
participant LvGridGenerator
participant ResultListener

== Init ==
Main -> OsmoGridGuardian: Run(cfg)
OsmoGridGuardian --> InputDataProvider: //Spawn//

OsmoGridGuardian --> ResultListener: //Spawn//
note right: Death watch of\n""ResultListener""

== LV generation ==
OsmoGridGuardian --> LvCoordinator: //Spawn//
OsmoGridGuardian -> LvCoordinator: <font color="red">!</font>ReqLvGrids(...)
LvCoordinator -> InputDataProvider: <font color="red">!</font>ReqOsm(...)
InputDataProvider <--> Input: //Read//
LvCoordinator -> InputDataProvider: <font color="red">!</font>ReqAssetTypes(...)
InputDataProvider <--> Input: //Read//
InputDataProvider -> LvCoordinator: <font color="red">!</font>RepOsm(...)
InputDataProvider -> LvCoordinator: <font color="red">!</font>RepAssetTypes(...)
note right: Determine the highest\nadministrative boundary //n//
LvCoordinator --> LvRegionCoordinator: //Spawn//

LvCoordinator -> LvRegionCoordinator: <font color="red">!</font>Partition(Region)
note right: //n// is the highest apparent\nadministrative boundary\nwithin OSM data
LvRegionCoordinator --> LvRegionCoordinator: //Spawn//
LvRegionCoordinator -> LvRegionCoordinator: <font color="red">!</font>Partition(Region, n')
... **Recursively spawn and divide regions until administrative boundary of a municipality is reached** ...

LvRegionCoordinator --> MunicipalityCoordinator: //Spawn one per municipality//
LvRegionCoordinator -> MunicipalityCoordinator: <font color="red">!</font>HandleMunicipality(Region)

MunicipalityCoordinator --> DistrictCoordinator: //Spawn one per district//
MunicipalityCoordinator -> DistrictCoordinator: <font color="red">!</font>HandleDistrict(Region)

DistrictCoordinator --> SubDistrictCoordinator: //Spawn one per sub district//
DistrictCoordinator -> SubDistrictCoordinator: <font color="red">!</font>HandleSubDistrict(Region)

SubDistrictCoordinator --> LvGridGenerator: //Spawn one per secondary//\n//substation region//
SubDistrictCoordinator -> LvGridGenerator: <font color="red">!</font>BuildGridModel(Region)

activate LvGridGenerator
... ...
LvGridGenerator -> LvCoordinator: <font color="red">!</font>RepLvGrid(...)
LvGridGenerator -> SubDistrictCoordinator: <font color="red">!</font>Done
note left: Collects completions until\nall secondarysubstation\nregions are handled\n\nCompletion messages can\nbe realized with death watch!
deactivate LvGridGenerator

SubDistrictCoordinator -> DistrictCoordinator: <font color="red">!</font>Done
DistrictCoordinator -> MunicipalityCoordinator: <font color="red">!</font>Done
MunicipalityCoordinator -> LvRegionCoordinator: <font color="red">!</font>Done
LvRegionCoordinator -> LvRegionCoordinator: <font color="red">!</font>Done
... **Report recursively until all intermediate levels are passed** ...
LvRegionCoordinator -> LvCoordinator: <font color="red">!</font>Done
note left: All results are apparent;\nassign sub grid numbers

LvCoordinator -> OsmoGridGuardian: <font color="red">!</font>RepLvGrids(...)

== MV generation ==
... **To be defined in a later stage** ...

== Result handling ==
OsmoGridGuardian -> ResultListener: <font color="red">!</font>GridResult(...)
activate ResultListener
... ...
ResultListener -> OsmoGridGuardian: <font color="red">!</font>ResultListenerDied
deactivate ResultListener
OsmoGridGuardian -> InputDataProvider: <font color="red">!</font>Terminate(...)
InputDataProvider <--> Input: //Close//
InputDataProvider -> OsmoGridGuardian: <font color="red">!</font>InputDataProviderDied

OsmoGridGuardian -> Main: <font color="red">!</font>Done

'TODO: Don't forget to spawn and initialize the ResultListener

@enduml
